[target.aarch64-apple-darwin]
rustflags = ['--cfg=curve25519_dalek_backend="u64"',
             "-C", "target-cpu=apple-m1",    
             "-C", "target-feature=+neon,+aes,+sha2,+crc,+fp16,+rcpc",
             "-Z", "tune-cpu=apple-m1",
             "--cfg=aes_armv8",
             ]

[target.x86_64-unknown-linux-gnu]
rustflags = ['--cfg=curve25519_dalek_backend="u64"', 
             "-C", "target-cpu=znver2", 
             "-C", "target-feature=+sse4.1,+aes,+ssse3,+fma,+bmi2,+avx2",
             "-Z", "tune-cpu=znver2",
             ]

## Intel CPU
# rustflags = [
#        '--cfg=curve25519_dalek_backend="simd"',  # u64 or simd
#        "-C", "target-cpu=sapphirerapids",
#        "-C", "target-feature=+sse4.2,+ssse3,+avx,+avx2,+fma,+bmi1,+bmi2,+aes,+pclmulqdq",
#        "-Z", "tune-cpu=sapphirerapids",  # use native
#]

[alias]
test-release = "test --release -- --nocapture"
tr = "test --release -- --nocapture"
tr-sh = "test --release -- --nocapture semi_honest_psu1"
tr-1m = "test --release -- --nocapture sender_malicious_psu1"
tr-2m = "test --release -- --nocapture malicious_psu2"
