[build]
rustflags = ['--cfg=curve25519_dalek_backend="simd"',
             "-C", "target-cpu=native",  # sapphirerapids, apple-m1, znver2, native
             "-Z", "tune-cpu=native",
            ]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon,+aes,+sha2,+crc,+fp16,+rcpc",
             "--cfg=aes_armv8",
             ]

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "target-feature=+avx512vl,+avx512ifma,+avx512f,+avx512dq,+avx512bw,+avx512vbmi,+avx512vnni,+avx512vpopcntdq,+aes,+sse4.2,+ssse3,+avx,+avx2,+fma,+bmi1,+bmi2,+pclmulqdq"]   


[target.'cfg(windows)']
rustflags = ["-C", "target-feature=+aes,+sse4.1,+ssse3,+fma,+bmi2,+avx,+avx2"]

[alias]
test-release = "test --release -- --nocapture"
tr = "test --release -- --nocapture"
tr-sh = "test --release -- --nocapture semi_honest_psu1"
tr-1m = "test --release -- --nocapture sender_malicious_psu1"
tr-2m = "test --release -- --nocapture malicious_psu2"
